# Copyright 2026 NextERP Romania
# License LGPL-3.0 or later
# (https://www.odoo.com/documentation/user/19.0/legal/licenses/licenses.html#).

from odoo import Command, fields, models
from odoo.exceptions import UserError


class MrpWorkorder(models.Model):
    _name = "mrp.workorder"
    _inherit = ["mrp.workorder", "l10n.ro.mixin"]

    def button_finish(self):
        ro_not_finished = self.filtered(
            lambda wo: wo.is_l10n_ro_record and wo.state != "done"
        )
        res = super().button_finish()
        for wo in ro_not_finished:
            if not wo.production_id.l10n_ro_auto_wip_accounting:
                continue
            # Post the raw material consumption at the end of each work order,
            # so stock and accounting entries happen together. Component WIP
            # entries are generated by the stock.move flow and are linked to
            # their stock move natively.
            wo._l10n_ro_post_inventory()
            # Labour cost is not backed by a stock move, so we create a
            # dedicated WIP entry linked to the work order.
            wo._l10n_ro_create_labour_wip_entry()
        return res

    def _l10n_ro_post_inventory(self):
        moves_not_available = self.move_raw_ids.filtered(
            lambda m: m.state not in ("assigned", "done", "cancel")
        )
        if moves_not_available:
            raise UserError(
                self.env._(
                    "Cannot finish the work order as some raw material moves are "
                    "not available.\nPlease check the availability of the "
                    "following moves:\n%(moves)s",
                    moves="\n".join(
                        f"- {move.raw_material_production_id.name} - "
                        f"{move.workorder_id.name} (Product: "
                        f"{move.product_id.display_name}, Qty: "
                        f"{move.product_uom_qty} {move.product_uom.name})"
                        for move in moves_not_available
                    ),
                )
            )
        moves_to_do = self.env["stock.move"]
        for move in self.move_raw_ids:
            if move.state == "assigned":
                move.picked = True
                moves_to_do |= move

        moves_to_do.with_context(skip_mo_check=True)._action_done()
        return True

    def _l10n_ro_create_labour_wip_entry(self):
        self.ensure_one()
        if not self.production_id.l10n_ro_auto_wip_accounting:
            return self.env["account.move"]
        cost = self._cal_cost()
        if self.company_id.currency_id.is_zero(cost):
            return self.env["account.move"]
        journal, wip_account, overhead_account = self._get_l10n_ro_wip_accounts()
        move_vals = self._prepare_l10n_ro_labour_move_vals(
            journal, wip_account, overhead_account, cost
        )
        move = self.env["account.move"].sudo().create(move_vals)
        move._post()
        return move

    def _get_l10n_ro_wip_accounts(self):
        company = (
            self.env["res.company"].browse(self._context.get("force_company"))
            or self.env.company
        )
        wip_product = self.production_id.product_id.with_company(self.company_id)
        accounts_data = wip_product.product_tmpl_id.sudo().get_product_accounts()
        wip_account = accounts_data.get("production_wip")
        if not wip_account:
            wip_account = (
                self.env["account.account"]
                .sudo()
                .with_company(company)
                .search(
                    [("company_id", "=", company.id), ("code", "like", "331%")],
                    limit=1,
                )
            )
        overhead_account = accounts_data.get(
            "production_wip_overhead"
        ) or accounts_data.get("expense")
        journal = accounts_data.get("stock_journal")
        if not journal:
            journal = (
                self.env["account.journal"]
                .sudo()
                .search(
                    [("type", "=", "general"), ("company_id", "=", company.id)],
                    limit=1,
                )
            )
        return journal, wip_account, overhead_account

    def _prepare_l10n_ro_labour_move_vals(
        self, journal, wip_account, overhead_account, cost
    ):
        self.ensure_one()
        description = self.env._(
            "WIP labour for Work Order: %(prod_name)s - %(workorder_name)s",
            prod_name=self.production_id.name,
            workorder_name=self.name,
        )
        if self.env.context.get("force_period_date"):
            date = self.env.context.get("force_period_date")
        elif self.date_finished:
            date = self.date_finished.date()
        else:
            date = fields.Date.context_today(self)
        line_vals = {
            "name": description,
            "product_id": self.production_id.product_id.id,
        }
        return {
            "journal_id": journal.id,
            "date": date,
            "move_type": "entry",
            "ref": description,
            "company_id": self.company_id.id,
            "l10n_ro_wip_workorder_id": self.id,
            "wip_production_ids": [Command.link(self.production_id.id)],
            "line_ids": [
                # Capitalise labour into WIP (331)
                Command.create(
                    {
                        **line_vals,
                        "account_id": wip_account.id,
                        "debit": cost,
                        "credit": 0.0,
                    }
                ),
                Command.create(
                    {
                        **line_vals,
                        "account_id": overhead_account.id,
                        "debit": 0.0,
                        "credit": cost,
                    }
                ),
            ],
        }
